import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.TRYNKA_CONFIG;
if(!cfg||cfg.supabaseUrl.includes('PASTE_')){document.body.innerHTML='<main><div class="panel"><h2>TRYNKA ONLINE</h2><p>Немає конфігурації Supabase.</p></div></main>';throw new Error('Supabase config missing')}
const sb=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
let user=null,profile=null,currentRoom=null,channel=null,lobbyChannel=null,countdownTimer=null,heartbeat=null,dealTimer=null,currentRound=null;
const $=id=>document.getElementById(id), sections=['login','lobby','profile','create','game'];
function show(id){sections.forEach(x=>$(x)?.classList.add('hide'));$(id)?.classList.remove('hide')}
function authView(w){$('authLogin').classList.toggle('hide',w!=='login');$('authRegister').classList.toggle('hide',w!=='register')}
$('showRegister').onclick=()=>authView('register'); $('showLogin').onclick=()=>authView('login');
async function boot(){const {data}=await sb.auth.getSession();if(data.session){user=data.session.user;await loadProfile()}else{show('login');authView('login')}}
$('registerForm').onsubmit=async e=>{e.preventDefault();const email=$('regEmail').value.trim().toLowerCase(),nickname=$('regNick').value.trim(),password=$('regPassword').value,password2=$('regPassword2').value;if(password!==password2)return alert('Паролі не співпадають');const {data,error}=await sb.auth.signUp({email,password,options:{data:{nickname}}});if(error)return alert(error.message);if(data.session){user=data.user;await sb.from('profiles').upsert({id:user.id,nickname});await loadProfile()}else{alert('Перевір пошту та підтвердь реєстрацію.');authView('login');$('loginEmail').value=email}};
$('loginForm').onsubmit=async e=>{e.preventDefault();const email=$('loginEmail').value.trim().toLowerCase(),password=$('loginPassword').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return alert('Не вдалося увійти. Перевір email, пароль і підтвердження пошти.');user=data.user;let {data:p}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!p)await sb.from('profiles').upsert({id:user.id,nickname:user.user_metadata?.nickname||email.split('@')[0].slice(0,20)});await loadProfile()};
$('logoutBtn').onclick=async()=>{if(currentRoom)await leaveRoom();clearInterval(heartbeat);await sb.auth.signOut();user=profile=null;$('logoutBtn').classList.add('hide');$('profileBtn').classList.add('hide');$('me').textContent='Гість';show('login')};
async function loadProfile(){const {data}=await sb.from('profiles').select('*').eq('id',user.id).single();profile=data;if(!profile)return;const {data:mod}=await sb.from('player_moderation').select('banned_until,reason').eq('user_id',user.id).maybeSingle();if(mod?.banned_until&&new Date(mod.banned_until)>new Date()){await sb.auth.signOut();alert('Акаунт тимчасово заблоковано'+(mod.reason?'\nПричина: '+mod.reason:''));show('login');return;} $('me').textContent=profile.nickname;$('logoutBtn').classList.remove('hide');$('profileBtn').classList.remove('hide');await pingOnline();clearInterval(heartbeat);heartbeat=setInterval(pingOnline,30000);show('lobby');await refreshLobby();await refreshAdminPanel();subscribeLobby()}
async function pingOnline(){if(user)await sb.from('profiles').update({online_at:new Date().toISOString()}).eq('id',user.id)}
$('profileBtn').onclick=async()=>{await renderProfile();show('profile')};document.querySelectorAll('.toLobby').forEach(b=>b.onclick=async()=>{show('lobby');await refreshLobby()});
async function renderProfile(){$('profileNick').textContent=profile.nickname;$('profileEmail').textContent=user.email||'';$('profileChips').textContent=profile.chips??0;$('profileGames').textContent=profile.games_played??0;$('profileWins').textContent=profile.wins??0;const {data:l}=await sb.from('chip_ledger').select('amount,balance_after,reason,created_at').order('created_at',{ascending:false}).limit(20);$('chipHistory').innerHTML=(l||[]).map(x=>'<div class="historyRow"><b>'+(x.amount>0?'+':'')+x.amount+' ◉</b><span>'+esc(x.reason)+' · баланс '+x.balance_after+'</span><small>'+new Date(x.created_at).toLocaleString('uk-UA')+'</small></div>').join('')||'<p>Операцій ще немає.</p>'}
$('newRoom').onclick=()=>show('create');
$('browseTables').onclick=()=>document.getElementById('tablesArea')?.scrollIntoView({behavior:'smooth'});
$('homeFriends').onclick=()=>document.getElementById('socialArea')?.scrollIntoView({behavior:'smooth'});
$('homeCabinet').onclick=async()=>{await renderProfile();show('profile')};
$('quickPlay').onclick=async()=>{const {data:rooms}=await sb.from('rooms').select('*,room_players(count)').order('created_at',{ascending:true});const open=(rooms||[]).find(r=>(r.room_players?.[0]?.count||0)>0&&(r.room_players?.[0]?.count||0)<r.max_players&&r.game_status!=='playing');if(open)return joinRoom(open);show('create')};
$('createForm').onsubmit=async e=>{e.preventDefault();const {data,error}=await sb.rpc('create_secure_room',{p_name:$('roomName').value.trim()||'Мій стіл',p_max_players:+$('maxPlayers').value,p_turn_seconds:+$('turnTime').value,p_ante:+$('ante').value});if(error)return alert(error.message);await openRoom(data)}
async function refreshLobby(){await pingOnline();const cutoff=new Date(Date.now()-70000).toISOString();const [{count:online},{data:rooms},{data:p}]=await Promise.all([sb.from('profiles').select('*',{count:'exact',head:true}).gt('online_at',cutoff),sb.from('rooms').select('*,room_players(count)').order('created_at',{ascending:false}),sb.from('profiles').select('*').eq('id',user.id).single()]);if(p)profile=p;if($('gameBalance'))$('gameBalance').textContent='◉ '+(profile?.chips??0);const n=online||0;$('onlineBadge').textContent='● '+n+' онлайн';$('onlineCount').textContent=n;$('onlineStat').textContent=n;$('myChips').textContent=profile?.chips??0;const active=(rooms||[]).filter(r=>(r.room_players?.[0]?.count||0)>0);$('tablesStat').textContent=active.length;$('rooms').innerHTML='';active.forEach(r=>{const count=r.room_players[0].count,d=document.createElement('div');d.className='roomCard';d.innerHTML='<div><div class="ownerLine"><span class="miniAvatar">♠</span><span>Відкритий стіл</span></div><h3>'+esc(r.name)+'</h3><div class="roomMeta"><span class="pill live">● Очікує</span><span class="pill">👥 '+count+'/'+r.max_players+'</span><span class="pill">◉ '+r.ante+'</span><span class="pill">⏱ '+r.turn_seconds+'с</span></div></div><button>Сісти</button>';d.querySelector('button').onclick=()=>joinRoom(r);$('rooms').appendChild(d)});if(!active.length)$('rooms').innerHTML='<p>Активних столів поки немає. Створи перший.</p>';await refreshFriends();await refreshInvites()}
async function joinRoom(r){const {error}=await sb.rpc('secure_join_room',{p_room:r.id});if(error)return alert(error.message);await openRoom(r.id)}
async function openRoom(id){currentRoom=id;show('game');if($('gameBalance'))$('gameBalance').textContent='◉ '+(profile?.chips??0);if(channel)await sb.removeChannel(channel);channel=sb.channel('room-'+id).on('postgres_changes',{event:'*',schema:'public',table:'room_players',filter:'room_id=eq.'+id},renderRoom).on('postgres_changes',{event:'*',schema:'public',table:'rooms',filter:'id=eq.'+id},renderRoom).on('postgres_changes',{event:'*',schema:'public',table:'room_hands',filter:'room_id=eq.'+id},renderHand).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'room_id=eq.'+id},p=>addMessage(p.new)).on('postgres_changes',{event:'*',schema:'public',table:'game_rounds',filter:'room_id=eq.'+id},renderRoom).subscribe();await renderRoom()}
async function renderRoom(){if(!currentRoom)return;const [{data:r},{data:ps}]=await Promise.all([sb.from('rooms').select('*').eq('id',currentRoom).single(),sb.from('room_players').select('user_id,seat_no,profiles(nickname)').eq('room_id',currentRoom)]);if(!r)return leaveRoom();$('roomTitle').textContent=r.name;const pot=(r.ante||0)*(ps||[]).filter(p=>p.seat_no!==null).length,fee=Math.floor(pot*((r.dealer_fee_percent??2)/100));if($('bankInfo'))$('bankInfo').textContent='Банк: '+pot+' ◉ · Дилер '+Number(r.dealer_fee_percent??2)+'%: '+fee+' ◉ · До виплати: '+Math.max(0,pot-fee)+' ◉';renderSeats(r,ps||[]);renderGameState(r,ps||[]);await renderRound(r,ps||[]);const {data:ms}=await sb.from('messages').select('*,profiles(nickname)').eq('room_id',currentRoom).order('created_at').limit(50);$('messages').innerHTML='';(ms||[]).forEach(addMessage);await renderHand(r)}
function renderSeats(r,ps){const bySeat=new Map(ps.filter(p=>p.seat_no!==null).map(p=>[p.seat_no,p]));$('seats').innerHTML='';for(let i=0;i<r.max_players;i++){const p=bySeat.get(i),d=document.createElement('div');d.className='seat s'+i+(p?.user_id===user.id?' mine':!p?' free':'');d.innerHTML=p?'<div class="seatName">'+(p.user_id===user.id?'★ ':'')+esc(p.profiles?.nickname||'Гравець')+((p.profiles?.nickname||'')==='Адмін'?'<span class="adminTag">ADMIN</span>':'')+'</div><div class="seatMeta">'+(p.user_id===user.id?'Ваше місце':'Гравець за столом')+'</div>':'<div class="seatName">＋ Сісти</div><div class="seatMeta">Вільне місце</div>';if(!p&&r.game_status!=='playing')d.onclick=()=>takeSeat(i);if(p&&p.user_id!==user.id){d.title='Натисни, щоб поскаржитися';d.onclick=()=>reportPlayer(p.user_id,p.profiles?.nickname||'Гравець')}$('seats').appendChild(d)}}
async function takeSeat(i){const {error}=await sb.rpc('take_room_seat',{p_room:currentRoom,p_seat:i});if(error)return alert(error.message);await sb.rpc('try_start_countdown',{p_room:currentRoom});await renderRoom()}
function renderGameState(r,ps){clearInterval(countdownTimer);const seated=ps.filter(p=>p.seat_no!==null).length;if(r.game_status==='waiting'){$('countdown').textContent=seated?'Очікуємо гравця':'Оберіть місце';$('turnStatus').textContent=seated<2?'Гра почнеться, коли сядуть двоє гравців':'';return}if(r.game_status==='countdown'){const tick=async()=>{const start=new Date(r.countdown_started_at).getTime(),left=Math.max(0,5-Math.floor((Date.now()-start)/1000));$('countdown').textContent='Старт через '+left;$('turnStatus').textContent='Готуємо карти…';if(left<=0){clearInterval(countdownTimer);await sb.rpc('deal_room_cards',{p_room:currentRoom});setTimeout(renderRoom,300)}};tick();countdownTimer=setInterval(tick,250);return}$('countdown').textContent='Гра почалась';$('turnStatus').textContent='Карти роздаються по одній'}
async function renderRound(r,ps){if(!$('gameActions'))return;const {data:gr}=await sb.from('game_rounds').select('*').eq('room_id',currentRoom).order('id',{ascending:false}).limit(1).maybeSingle();currentRound=gr;if(!gr||gr.status!=='playing'){$('gameActions').classList.add('hide');if(gr?.status==='finished')$('turnStatus').textContent='Роздачу завершено';return}$('gameActions').classList.remove('hide');const turn=ps.find(p=>p.user_id===gr.turn_user_id);$('roundPot').textContent='Банк: '+gr.pot+' ◉';$('roundBet').textContent='Поточна ставка: '+gr.current_bet+' ◉';$('roundTurn').textContent=gr.turn_user_id===user.id?'Ваш хід':('Хід: '+(turn?.profiles?.nickname||'гравця'));const mine=gr.turn_user_id===user.id;document.querySelectorAll('#gameActions button[data-action]').forEach(b=>{b.disabled=!mine||(b.dataset.action==='reveal'&&Number(gr.round_no||1)<2);if(b.dataset.action==='reveal')b.title=Number(gr.round_no||1)<2?'Вскриття доступне з другого кола':''})}
async function doGameAction(action){if(!currentRoom)return;let raiseTo=null;if(action==='raise'){raiseTo=Number(prompt('До якої загальної ставки підняти?'));if(!raiseTo)return}const {error}=await sb.rpc('play_round_action',{p_room:currentRoom,p_action:action,p_raise_to:raiseTo});if(error)return alert(error.message);await renderRoom()}
document.querySelectorAll('#gameActions button[data-action]').forEach(b=>b.onclick=()=>doGameAction(b.dataset.action));
async function renderHand(roomArg){if(!currentRoom)return;const r=roomArg?.id?roomArg:(await sb.from('rooms').select('*').eq('id',currentRoom).single()).data;if(!r||r.game_status!=='playing'){$('myHand').innerHTML='';return}const {data:h}=await sb.from('room_hands').select('cards').eq('room_id',currentRoom).eq('user_id',user.id).maybeSingle();if(!h)return;clearInterval(dealTimer);const draw=()=>{const elapsed=Math.max(0,Date.now()-new Date(r.deal_started_at).getTime()),visible=Math.min(3,Math.floor(elapsed/650)+1);$('myHand').innerHTML=h.cards.slice(0,visible).map(c=>'<div class="card '+(/[♠♣]/.test(c)?'black':'')+'">'+esc(c)+'</div>').join('');if(visible>=3)clearInterval(dealTimer)};draw();dealTimer=setInterval(draw,120)}
async function leaveRoom(){clearInterval(countdownTimer);clearInterval(dealTimer);if(currentRoom&&user){const rid=currentRoom;await sb.rpc('secure_leave_room',{p_room:rid});currentRoom=null}if(channel){await sb.removeChannel(channel);channel=null}show('lobby');await refreshLobby()}
$('leaveRoom').onclick=leaveRoom;
$('chatForm').onsubmit=async e=>{e.preventDefault();const body=$('chatInput').value.trim();if(!body)return;const {error}=await sb.rpc('send_chat_message',{p_room:currentRoom,p_body:body});if(error)return alert(error.message);$('chatInput').value=''}
function addMessage(m){const p=document.createElement('p');p.textContent=(m.profiles?.nickname||profile?.nickname||'Гравець')+': '+m.body;$('messages').appendChild(p);$('messages').scrollTop=$('messages').scrollHeight}
$('friendForm').onsubmit=async e=>{e.preventDefault();const n=$('friendNick').value.trim();const {data:p}=await sb.from('profiles').select('id,nickname').eq('nickname',n).maybeSingle();if(!p)return alert('Гравця не знайдено');if(p.id!==user.id)await sb.from('friends').upsert({user_id:user.id,friend_id:p.id});$('friendNick').value='';refreshFriends()}
async function refreshFriends(){const {data}=await sb.from('friends').select('friend_id,profiles!friends_friend_id_fkey(nickname)').eq('user_id',user.id);$('friends').innerHTML=(data||[]).map(f=>'<div class="friend">● <b>'+esc(f.profiles.nickname)+'</b></div>').join('')||'<p>Друзів ще немає.</p>'}
$('inviteBtn').onclick=async()=>{const {data}=await sb.from('friends').select('friend_id,profiles!friends_friend_id_fkey(nickname)').eq('user_id',user.id);$('inviteFriends').innerHTML='';(data||[]).forEach(f=>{const b=document.createElement('button');b.textContent='Запросити '+f.profiles.nickname;b.onclick=async()=>{await sb.from('invites').insert({room_id:currentRoom,from_user:user.id,to_user:f.friend_id});b.disabled=true;b.textContent='Запрошено ✓'};$('inviteFriends').appendChild(b)});$('inviteDialog').showModal()}
async function refreshInvites(){const {data}=await sb.from('invites').select('id,room_id,profiles!invites_from_user_fkey(nickname),rooms(name)').eq('to_user',user.id).eq('status','pending');$('invites').innerHTML='';(data||[]).forEach(i=>{const d=document.createElement('div');d.className='invite';d.innerHTML='<b>'+esc(i.profiles.nickname)+'</b> запрошує: '+esc(i.rooms?.name||'стіл')+' ';const b=document.createElement('button');b.textContent='Прийняти';b.onclick=async()=>{await sb.from('invites').update({status:'accepted'}).eq('id',i.id);const {error}=await sb.rpc('secure_join_room',{p_room:i.room_id});if(error)return alert(error.message);await openRoom(i.room_id)};d.appendChild(b);$('invites').appendChild(d)});if(!$('invites').children.length)$('invites').innerHTML='<p>Немає нових.</p>'}
function subscribeLobby(){if(lobbyChannel)sb.removeChannel(lobbyChannel);lobbyChannel=sb.channel('lobby-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:'rooms'},refreshLobby).on('postgres_changes',{event:'*',schema:'public',table:'room_players'},refreshLobby).on('postgres_changes',{event:'INSERT',schema:'public',table:'invites',filter:'to_user=eq.'+user.id},refreshInvites).subscribe()}
$('contactAdmin').onclick=()=>$('adminDialog').showModal();$('closeAdminDialog').onclick=()=>$('adminDialog').close();$('adminRequestForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.rpc('create_chip_request',{p_amount:+$('chipAmount').value,p_message:$('adminRequestText').value.trim()});if(error)return alert(error.message);$('adminDialog').close();alert('Заявку надіслано адміну ✓')}
async function refreshAdminPanel(){if(!profile)return;const {data:isAdmin}=await sb.rpc('is_admin');if(!isAdmin){$('adminPanel').classList.add('hide');return}$('adminPanel').classList.remove('hide');const {data}=await sb.from('chip_requests').select('id,user_id,amount,message,profiles(nickname)').eq('status','pending').order('created_at');$('chipRequests').innerHTML='';(data||[]).forEach(r=>{const d=document.createElement('div');d.className='invite';d.innerHTML='<b>'+esc(r.profiles?.nickname||'Гравець')+'</b> — '+r.amount+' ◉ ';const b=document.createElement('button');b.textContent='Нарахувати';b.onclick=async()=>{const {error}=await sb.rpc('grant_virtual_chips',{target_user:r.user_id,chip_amount:r.amount,request_id:r.id});if(error)return alert(error.message);refreshAdminPanel()};d.appendChild(b);$('chipRequests').appendChild(d)});if(!$('chipRequests').children.length)$('chipRequests').innerHTML='<p>Нових заявок немає.</p>';await refreshSecurityAdmin();await refreshAdminRooms()}
async function reportPlayer(id,nick){const reason=prompt('Причина скарги на '+nick+':');if(!reason)return;const {error}=await sb.rpc('report_player',{p_reported:id,p_room:currentRoom,p_reason:reason});alert(error?error.message:'Скаргу надіслано адміну ✓')}
async function refreshSecurityAdmin(){if(!$('securityAdmin'))return;const [{data:reports},{data:events}]=await Promise.all([sb.from('player_reports').select('id,reported_id,reason,created_at,profiles!player_reports_reported_id_fkey(nickname)').eq('status','open').order('created_at',{ascending:false}).limit(20),sb.from('security_events').select('event_type,detail,created_at').order('created_at',{ascending:false}).limit(20)]);$('securityAdmin').innerHTML='<h4>Скарги</h4>'+((reports||[]).map(r=>'<div class="historyRow"><b>'+esc(r.profiles?.nickname||'Гравець')+'</b><span>'+esc(r.reason)+'</span><div><button onclick="window.modPlayer(\''+r.reported_id+'\',\'mute\')">Мут 1 год</button> <button onclick="window.modPlayer(\''+r.reported_id+'\',\'ban\')">Бан 24 год</button> <button onclick="window.resolveReport('+r.id+')">Закрити скаргу</button></div></div>').join('')||'<p>Скарг немає.</p>')+'<h4>Події безпеки</h4>'+((events||[]).map(e=>'<div class="historyRow"><b>'+esc(e.event_type)+'</b><span>'+esc(e.detail||'')+'</span><small>'+new Date(e.created_at).toLocaleString('uk-UA')+'</small></div>').join('')||'<p>Подій немає.</p>')}
window.modPlayer=async(id,action)=>{const minutes=action==='mute'?60:1440;const reason=prompt('Причина:')||'Порушення правил';const {error}=await sb.rpc('admin_set_moderation',{p_user:id,p_action:action,p_minutes:minutes,p_reason:reason});alert(error?error.message:'Застосовано ✓');refreshSecurityAdmin()}
window.resolveReport=async id=>{const {error}=await sb.rpc('admin_resolve_report',{p_report:id,p_status:'closed'});if(error)alert(error.message);refreshSecurityAdmin()}
async function refreshAdminRooms(){if(!$('adminRooms'))return;const {data}=await sb.from('rooms').select('id,name,room_players(count)').order('created_at',{ascending:false}).limit(30);$('adminRooms').innerHTML=(data||[]).map(r=>'<div class="adminRow"><span><b>'+esc(r.name)+'</b> · '+(r.room_players?.[0]?.count||0)+' гравців</span><button onclick="window.closeRoom('+r.id+')">Закрити</button></div>').join('')||'<p>Столів немає.</p>'}
window.closeRoom=async id=>{if(!confirm('Закрити цей стіл? Активні віртуальні ставки буде повернено.'))return;const {error}=await sb.rpc('admin_close_room',{p_room:id});alert(error?error.message:'Стіл закрито ✓');refreshAdminRooms()}
$('adminFindPlayer').onclick=async()=>{const n=$('adminPlayerSearch').value.trim();if(!n)return;const {data:p}=await sb.from('profiles').select('id,nickname,chips,games_played,wins').eq('nickname',n).maybeSingle();if(!p){$('adminPlayerResult').innerHTML='<p>Не знайдено.</p>';return}$('adminPlayerResult').innerHTML='<div class="adminPlayer"><b>'+esc(p.nickname)+'</b><span>'+p.chips+' ◉ · '+p.games_played+' ігор · '+p.wins+' перемог</span><div><button onclick="window.adjustChips(\''+p.id+'\')">± Фішки</button> <button onclick="window.adminMod(\''+p.id+'\',\'mute\')">Мут</button> <button onclick="window.adminMod(\''+p.id+'\',\'ban\')">Бан</button> <button onclick="window.adminMod(\''+p.id+'\',\'unmute\')">Зняти мут</button> <button onclick="window.adminMod(\''+p.id+'\',\'unban\')">Розбан</button></div></div>'}
window.adjustChips=async id=>{const amount=Number(prompt('Зміна віртуальних фішок. Наприклад 500 або -500:'));if(!amount)return;const reason=prompt('Причина:')||'Адмін-коригування';const {error}=await sb.rpc('admin_adjust_virtual_chips',{p_user:id,p_amount:amount,p_reason:reason});alert(error?error.message:'Баланс змінено ✓')}
window.adminMod=async(id,action)=>{let mins=0;if(action==='mute'||action==='ban'){mins=Number(prompt('На скільки хвилин?',action==='mute'?'60':'1440'));if(!mins)return}const reason=prompt('Причина:')||'Адмін-модерація';const {error}=await sb.rpc('admin_set_moderation',{p_user:id,p_action:action,p_minutes:mins,p_reason:reason});alert(error?error.message:'Готово ✓')}
$('chatCollapse').onclick=()=>document.querySelector('#game .chat')?.classList.toggle('collapsed');
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
boot();