import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.TRYNKA_CONFIG;if(!cfg)return;const sb=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const $=id=>document.getElementById(id);
let soundOn=localStorage.getItem('trynkaSound')!=='off';
function tone(freq=440,dur=.07,vol=.025){if(!soundOn)return;try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.stop(a.currentTime+dur)}catch{}}
function addSoundButton(){const h=document.querySelector('header>div');if(!h||$('soundToggle'))return;const b=document.createElement('button');b.id='soundToggle';b.className='soundToggle';b.textContent=soundOn?'🔊':'🔇';b.title='Звук гри';b.onclick=()=>{soundOn=!soundOn;localStorage.setItem('trynkaSound',soundOn?'on':'off');b.textContent=soundOn?'🔊':'🔇';tone(520)};h.prepend(b)}
document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('#soundToggle'))tone(420,.045,.015)});
function observeGame(){const target=$('game');if(!target)return;let oldCards=0,oldPot='';new MutationObserver(()=>{if(target.classList.contains('hide'))return;const cards=document.querySelectorAll('#myHand .card').length,pot=$('potBig')?.textContent||'';if(cards>oldCards)tone(620+cards*80,.08,.02);if(oldPot&&pot!==oldPot)tone(260,.06,.018);oldCards=cards;oldPot=pot}).observe(target,{subtree:true,childList:true,characterData:true});}
async function leaderboard(){let box=$('leaderboardBox');if(!box){const area=$('tablesArea');if(!area)return;box=document.createElement('section');box.id='leaderboardBox';box.className='leaderboardBox';area.after(box)}const {data,error}=await sb.from('profiles').select('nickname,wins,games_played,chips').order('wins',{ascending:false}).limit(10);if(error){box.innerHTML='';return}const rows=(data||[]).map((p,i)=>`<div class="rankRow"><span class="rankPos">${i+1}</span><b>${escapeHtml(p.nickname||'Гравець')}</b><span>${p.wins||0} перемог</span><small>${p.games_played||0} ігор</small></div>`).join('');box.innerHTML=`<div class="rankHead"><div><span class="eyebrow">RANKING</span><h2>Топ гравців</h2></div><span>За перемогами</span></div><div class="rankList">${rows||'<p>Рейтинг поки порожній</p>'}</div>`}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function adminNav(){const a=$('adminPanel');if(!a||$('adminJump'))return;const n=document.createElement('div');n.id='adminJump';n.className='adminJump';n.innerHTML='<button data-go="chipRequests">◉ Фішки</button><button data-go="adminPlayerSearch">👤 Гравці</button><button data-go="adminRooms">♠ Столи</button><button data-go="securityAdmin">⚑ Безпека</button>';n.onclick=e=>{const id=e.target.closest('button')?.dataset.go;if(id)$(id)?.scrollIntoView({behavior:'smooth',block:'center'})};a.querySelector('.adminHero')?.after(n)}
function init(){addSoundButton();observeGame();adminNav();leaderboard();setInterval(()=>{if(!$('lobby')?.classList.contains('hide'))leaderboard();adminNav()},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();