import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const sb=createClient(window.TRYNKA_CONFIG.supabaseUrl,window.TRYNKA_CONFIG.supabaseAnonKey); const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function session(){return (await sb.auth.getSession()).data.session?.user}
async function renderExtras(){const lobby=$('lobby');if(!lobby||lobby.classList.contains('hide'))return;let box=$('trynkaExtras');if(!box){box=document.createElement('section');box.id='trynkaExtras';box.className='extrasGrid';box.innerHTML='<div class="panel"><div class="historyHead"><h2>🏆 Рейтинг</h2><span>ТОП 10</span></div><div id="leagueBoard"></div></div><div class="panel"><div class="historyHead"><h2>🔐 Приватний стіл</h2><span>Код друга</span></div><div class="joinCode"><input id="privateCode" maxlength="6" placeholder="Напр. A1B2C3"><button id="joinPrivate">Увійти</button></div><p class="muted">Приватні столи та запрошення кодом уже підтримуються сервером.</p></div><div class="panel"><div class="historyHead"><h2>🎖 Досягнення</h2><span>Прогрес</span></div><div id="achievementsMini">Перша перемога · 10 перемог · 666 · Темна · Серія ×5</div></div><div class="panel"><div class="historyHead"><h2>🏟 Турніри</h2><span>8 / 16</span></div><div id="tournamentMini">Турнірна система підключена. Реєстрація та сітка зʼявляться тут.</div></div>';lobby.querySelector('.lobbyShell')?.appendChild(box);$('joinPrivate').onclick=async()=>{const code=$('privateCode').value.trim();if(!code)return;const {data,error}=await sb.rpc('join_room_by_code',{p_code:code});if(error)return alert(error.message);location.hash='room-'+data;location.reload()}}
 const {data:top}=await sb.from('profiles').select('nickname,wins,games_played,xp,level').eq('is_bot',false).order('wins',{ascending:false}).limit(10);$('leagueBoard').innerHTML=(top||[]).map((p,i)=>`<div class="rankRow"><b>${i+1}. ${esc(p.nickname)}</b><span>${p.wins||0} перемог · Lv.${p.level||1}</span></div>`).join('')||'Ще немає рейтингу.';
}
async function enhanceGame(){const game=$('game');if(!game||game.classList.contains('hide'))return;let bar=$('socialGameBar');if(!bar){bar=document.createElement('div');bar.id='socialGameBar';bar.className='socialGameBar';bar.innerHTML='<span>Реакції:</span>'+['👍','😂','😡','😎','👏'].map(x=>`<button data-e="${x}">${x}</button>`).join('')+'<button id="readyToggle" class="ghostBtn">✓ ГОТОВИЙ</button>';game.querySelector('.gameBar')?.after(bar);bar.querySelectorAll('[data-e]').forEach(b=>b.onclick=async()=>{const room=window.location.hash.match(/room-(\d+)/)?.[1];if(room)await sb.rpc('send_table_reaction',{p_room:+room,p_emoji:b.dataset.e})})}}
setInterval(()=>{renderExtras();enhanceGame()},1500);renderExtras();enhanceGame();
