import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.TRYNKA_CONFIG;
if(!cfg) throw new Error('Missing config');
const sb=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
let me=null,standing=false,timerState=null,lastTimerText='',syncBusy=false;
const $=id=>document.getElementById(id);

async function getMe(){if(me)return me;const {data}=await sb.auth.getSession();me=data.session?.user||null;return me}
async function seatedRoom(){const u=await getMe();if(!u)return null;const {data}=await sb.from('room_players').select('room_id,seat_no').eq('user_id',u.id).not('seat_no','is',null).order('joined_at',{ascending:false}).limit(1).maybeSingle();return data||null}
async function syncButtons(){const leave=$('leaveRoom'),stand=$('standUpBtn');if(!leave||!stand)return;const rp=await seatedRoom();const seated=!!rp;stand.classList.toggle('hide',!seated);leave.classList.toggle('lobbyLocked',seated);leave.textContent=seated?'🔒 Спочатку встаньте':'← Лобі';leave.title=seated?'Щоб вийти в лобі, спочатку встаньте зі столу':''}
function mount(){const actions=document.querySelector('.gameTopActions');if(!actions||$('standUpBtn'))return;const b=document.createElement('button');b.id='standUpBtn';b.className='standUpBtn hide';b.textContent='↑ Встати зі столу';actions.prepend(b);b.addEventListener('click',async()=>{if(standing)return;const rp=await seatedRoom();if(!rp)return syncButtons();standing=true;b.disabled=true;b.textContent='Встаємо…';const {error}=await sb.rpc('stand_up_from_table',{p_room:rp.room_id});standing=false;b.disabled=false;if(error){b.textContent='↑ Встати зі столу';alert(error.message);return}b.classList.add('hide');const leave=$('leaveRoom');if(leave){leave.classList.remove('lobbyLocked');leave.textContent='← Лобі';leave.title=''};timerState=null;setTimeout(syncButtons,250)});}
function cleanRemovedActions(){document.querySelectorAll('[data-action="dark"],[data-action="boil"]').forEach(x=>x.remove());document.querySelectorAll('#tableActionLog .actionLogRow').forEach(row=>{const t=row.textContent||'';if(t.includes('темну')||t.includes('варити'))row.remove()})}
function addStableTimerCss(){if($('stableTimerCss'))return;const s=document.createElement('style');s.id='stableTimerCss';s.textContent='#roundTurn{display:inline-block!important;min-width:185px!important;height:20px!important;line-height:20px!important;opacity:1!important;visibility:visible!important;animation:none!important;transition:none!important;transform:none!important;white-space:nowrap!important;font-variant-numeric:tabular-nums!important;contain:layout paint!important}#roundTurn *{animation:none!important;transition:none!important}';document.head.appendChild(s)}
async function syncTimerState(){if(syncBusy||!me||$('game')?.classList.contains('hide'))return;syncBusy=true;try{const rp=await seatedRoom();if(!rp){timerState=null;return}const [{data:r},{data:gr}]=await Promise.all([sb.from('rooms').select('turn_seconds').eq('id',rp.room_id).maybeSingle(),sb.from('game_rounds').select('id,status,turn_user_id,turn_started_at,created_at').eq('room_id',rp.room_id).order('id',{ascending:false}).limit(1).maybeSingle()]);if(!gr||gr.status!=='playing'){timerState=null;return}let nick='гравця';if(gr.turn_user_id!==me.id){const {data:p}=await sb.from('profiles').select('nickname').eq('id',gr.turn_user_id).maybeSingle();nick=p?.nickname||'гравця'}timerState={roundId:gr.id,turnUser:gr.turn_user_id,started:new Date(gr.turn_started_at||gr.created_at).getTime(),seconds:Number(r?.turn_seconds||30),nick};}finally{syncBusy=false}}
function paintTimer(){const el=$('roundTurn');if(!el||!timerState)return;const left=Math.max(0,timerState.seconds-Math.floor((Date.now()-timerState.started)/1000));const text=(timerState.turnUser===me?.id?'Ваш хід':'Хід: '+timerState.nick)+' · '+left+'с';if(text!==lastTimerText){el.textContent=text;lastTimerText=text}}
// Block Lobby before the player stands up.
document.addEventListener('click',async e=>{const b=e.target.closest('#leaveRoom');if(!b)return;const rp=await seatedRoom();if(rp){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();alert('Спочатку натисніть «Встати зі столу», а потім можна вийти в лобі.')}},true);
async function init(){mount();addStableTimerCss();cleanRemovedActions();await getMe();await syncButtons();await syncTimerState();new MutationObserver(cleanRemovedActions).observe(document.body,{childList:true,subtree:true});setInterval(()=>{if(!$('game')?.classList.contains('hide'))syncButtons()},1500);setInterval(syncTimerState,1200);setInterval(paintTimer,200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();